name: smos
channels:
  - conda-forge
dependencies:
- numpy>=1.13.0
- pandas
- netcdf4
- scipy
- pyresample
- pip:
    - pygeobase
    - pynetcf
    - repurpose
    - trollsift
    - ease_grid
    - more_itertools