name: smos
channels:
  - defaults
  - conda-forge
dependencies:
- numpy
- pandas
- netCDF4!=1.6.2
- hdf5
- scipy
- dask[distributed]
- xarray
- pyresample
- pip
- pip:
    - pygeobase
    - pygeogrids
    - pynetcf
    - pyproj
    - repurpose>=0.13.1
    - trollsift
    - ease_grid
    - more_itertools
    - cf-xarray
    - qa4sm_preprocessing>=0.5
